-- Inserir solicitações de exemplo para teste
INSERT INTO public.requests (
    titulo,
    descricao,
    status,
    prioridade,
    categoria,
    origem_canal,
    solicitante_id,
    equipe_solicitante,
    justificativa_negocio,
    objetivo_estrategico,
    relevancia_financeira,
    impacto_estimado,
    status_curadoria,
    classificacao_dado,
    estimativa_entrega,
    proposito_de_uso
) VALUES 
(
    'Análise de Ticket Médio por Região',
    'Preciso de uma análise detalhada do ticket médio de vendas segmentado por região geográfica para otimizar campanhas de marketing regional. Os dados devem incluir tendências dos últimos 12 meses e comparação com o ano anterior.',
    'em_desenvolvimento',
    'alta',
    ARRAY['Vendas', 'Regional', 'Marketing'],
    'chat',
    (SELECT id FROM auth.users LIMIT 1),
    'Equipe de CRM',
    'Identificar regiões com maior potencial de crescimento e ajustar estratégias de pricing regional',
    'aumento_de_conversao',
    'Impacto estimado de R$ 500K em revenue adicional',
    'validado',
    'nao_sensivel',
    NOW() + INTERVAL '2 days',
    'Análise estratégica para direcionamento de campanhas de marketing'
),
(
    'Base de Clientes Inativos com Motivos de Churn',
    'Base consolidada de clientes que não fizeram compras nos últimos 6 meses, incluindo análise de motivos de churn baseada em interações de suporte e padrões de comportamento.',
    'pendente',
    'normal',
    ARRAY['Clientes', 'Churn', 'Retenção'],
    'formulario_web',
    (SELECT id FROM auth.users LIMIT 1),
    'Customer Success',
    'Desenvolver estratégias de reativação de clientes e reduzir taxa de churn',
    'reduzir_churn',
    'Redução potencial de 15% na taxa de churn',
    'aguardando',
    'PII',
    NOW() + INTERVAL '5 days',
    'Estratégia de retenção e reativação de clientes'
),
(
    'Dashboard de Abandono de Carrinho por Categoria',
    'Dashboard interativo mostrando taxa de abandono de carrinho segmentado por categoria de produto, horário do dia e dispositivo utilizado. Incluir funil de conversão detalhado.',
    'concluida',
    'normal',
    ARRAY['E-commerce', 'Conversão', 'UX'],
    'chat',
    (SELECT id FROM auth.users LIMIT 1),
    'Product Analytics',
    'Otimizar fluxo de checkout e reduzir abandono de carrinho',
    'aumento_de_conversao',
    'Aumento potencial de 8% na conversão',
    'validado',
    'nao_sensivel',
    NOW() - INTERVAL '1 day',
    'Otimização da experiência de checkout'
),
(
    'Relatório Automatizado de Performance Semanal',
    'Relatório automatizado com métricas de performance de vendas, marketing e produto enviado semanalmente para stakeholders. Incluir alertas para métricas fora do padrão.',
    'cancelada',
    'baixa',
    ARRAY['Performance', 'Automação', 'Relatórios'],
    'api',
    (SELECT id FROM auth.users LIMIT 1),
    'Business Intelligence',
    'Automatizar reporting semanal e liberar tempo da equipe de BI',
    'eficiencia_operacional',
    'Economia de 20h/semana da equipe de BI',
    'reprovado',
    'nao_sensivel',
    NULL,
    'Automação de processos de reporting'
),
(
    'Análise de Rentabilidade por SKU',
    'Análise detalhada de rentabilidade por SKU incluindo custos de aquisição, armazenagem, logística e margem líquida. Dados dos últimos 24 meses para identificar produtos mais/menos rentáveis.',
    'em_curadoria',
    'alta',
    ARRAY['Financeiro', 'Produto', 'Rentabilidade'],
    'chat',
    (SELECT id FROM auth.users LIMIT 1),
    'Controladoria',
    'Otimizar mix de produtos e identificar SKUs para descontinuar ou promover',
    'eficiencia_operacional',
    'Otimização potencial de R$ 2M em margem',
    'em_curadoria',
    'financeiro',
    NOW() + INTERVAL '7 days',
    'Análise estratégica de portfólio de produtos'
),
(
    'Segmentação de Clientes por Valor de Lifetime',
    'Segmentação avançada de base de clientes baseada em CLV (Customer Lifetime Value), frequência de compra, ticket médio e tendência de crescimento. Incluir modelos preditivos.',
    'pendente',
    'urgente',
    ARRAY['Clientes', 'CLV', 'Segmentação', 'Machine Learning'],
    'formulario_web',
    (SELECT id FROM auth.users LIMIT 1),
    'Data Science',
    'Personalizar estratégias de marketing e pricing baseado no valor do cliente',
    'aumento_de_conversao',
    'Aumento estimado de 25% no ROAS de campanhas',
    'aguardando',
    'PII',
    NOW() + INTERVAL '10 days',
    'Personalização de estratégias comerciais baseada em valor do cliente'
);